[package]
name = "const-rollup-config"
version = "0.3.0"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["Sovereign Labs <info@sovereign.xyz>"]
publish = false

[dependencies]
hex-literal = "0.3.4"
