name: build-test-linux-stable

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    name: fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cargo fmt --version
      - run: cargo fmt --all -- --check
  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get install protobuf-compiler
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: rustup target add wasm32-unknown-unknown
      - run: rustup install nightly && rustup target add wasm32-unknown-unknown --toolchain nightly
      - run: cargo build --verbose --workspace
      - run: cargo test --verbose --workspace
